serializerFeatures:
  - QuoteFieldNames
  - WriteMapNullValue
  - WriteNullStringAsEmpty
  - WriteNullBooleanAsFalse
  - WriteNullListAsEmpty
  - WriteNullNumberAsZero
  - WriteDateUseDateFormat
  - DisableCircularReferenceDetect